version: "3.9"

services:
  frontend:
    image: esteban1930/nebula-frontend:latest
    container_name: test-nebula-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost/api/backend
      VITE_NOTIFICATION_BASE_URL: http://localhost/api/notifications
      VITE_VAPID_PUBLIC_KEY: BBYxHayr8UXJerM06-l8YNLTxEQA5zS3xW4u29rUXxPZsDsSXDYghf0Pvb8imkub4MboWOzlSvU7XsHhCJHXLz4
    ports:
      - "8095:80"